<a href="https://colab.research.google.com/github/rahulpirwani7/Student-Pass-Fail-Prediction/blob/main/Passandfailpredication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import kagglehub
import os
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("souradippal/student-performance-prediction")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'student-performance-prediction' dataset.
Path to dataset files: /kaggle/input/student-performance-prediction

In [112]:
files = os.listdir(path)

print("\nFiles in the dataset:")
for file in files:
    print(file)

csv_file = None
for file in files:
    if file.endswith(".csv"):
        csv_file = file
        break

if csv_file is None:
    print("No CSV file found in the dataset.")
else:
    file_path = os.path.join(path, csv_file)
    df = pd.read_csv(file_path)

Files in the dataset:
student_performance_prediction.csv

In [113]:
df.columns=df.columns.tolist()
df.drop('Student ID',axis=1,inplace=True)
df.dropna(subset=['Passed','Participation in Extracurricular Activities'],inplace=True)

In [114]:
df

,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,12.5,NaN,75.0,Yes,Master,Yes
1,9.3,95.3,60.6,No,High School,No
2,13.2,NaN,64.0,No,Associate,No
3,17.6,76.8,62.4,Yes,Bachelor,No
4,8.8,89.3,72.7,No,Master,No
...,...,...,...,...,...,...
39995,15.6,93.8,51.4,Yes,Master,No
39996,11.3,66.4,64.2,No,Doctorate,Yes
39997,13.1,65.6,38.1,No,Bachelor,No
39998,14.1,74.9,NaN,Yes,Master,No
39999,11.8,55.1,68.5,No,Bachelor,Yes

In [115]:
df.describe()

       Study Hours per Week  Attendance Rate  Previous Grades
count          34305.000000     34296.000000     34313.000000
mean               9.961991        75.306097        65.456209
std                5.036045        20.452881        16.569593
min              -12.300000       -14.300000         8.300000
25%                6.600000        61.500000        55.100000
50%               10.000000        75.300000        65.200000
75%               13.400000        88.800000        75.200000
max               32.400000       150.200000       200.000000

In [116]:
X = ['Study Hours per Week', 'Attendance Rate', 'Previous Grades']

for col in X:
    mean = df[col].mean()
    df[col] = df[col].fillna(mean)
    df.loc[(df[col] < 0) | (df[col] > 100), col] = mean

In [117]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Participation in Extracurricular Activities']=le.fit_transform(df['Participation in Extracurricular Activities'])
df['Passed']=le.fit_transform(df['Passed'])

In [118]:
df.describe()

,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Passed
count,36098.000000,36098.000000,36098.000000,36098.000000,36098.000000
mean,10.241374,71.633668,64.720242,0.499529,0.499695
std,4.543615,15.551990,14.073590,0.500007,0.500007
min,-0.000000,0.500000,8.300000,0.000000,0.000000
25%,7.100000,62.400000,55.700000,0.000000,0.000000
50%,9.961991,75.306097,65.456209,0.000000,0.000000
75%,13.200000,81.800000,74.000000,1.000000,1.000000
max,32.400000,100.000000,100.000000,1.000000,1.000000

In [119]:
df = pd.get_dummies(
    df,
    columns=["Parent Education Level"],
    prefix="",
    prefix_sep="",
    dtype=int
)

In [120]:
df.describe()

,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Passed,Associate,Bachelor,Doctorate,High School,Master
count,36098.000000,36098.000000,36098.000000,36098.000000,36098.000000,36098.000000,36098.000000,36098.000000,36098.000000,36098.000000
mean,10.241374,71.633668,64.720242,0.499529,0.499695,0.191008,0.192033,0.190869,0.191036,0.185412
std,4.543615,15.551990,14.073590,0.500007,0.500007,0.393101,0.393904,0.392992,0.393122,0.388637
min,-0.000000,0.500000,8.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.100000,62.400000,55.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,9.961991,75.306097,65.456209,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,13.200000,81.800000,74.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,32.400000,100.000000,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [121]:
from sklearn.model_selection import train_test_split
X = df.drop('Passed', axis=1)
y = df['Passed']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [122]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [135]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5081921798321988

In [124]:
df

,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Passed,Associate,Bachelor,Doctorate,High School,Master
0,12.5,75.306097,75.000000,1,1,0,0,0,0,1
1,9.3,95.300000,60.600000,0,0,0,0,0,1,0
2,13.2,75.306097,64.000000,0,0,1,0,0,0,0
3,17.6,76.800000,62.400000,1,0,0,1,0,0,0
4,8.8,89.300000,72.700000,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
39995,15.6,93.800000,51.400000,1,0,0,0,0,0,1
39996,11.3,66.400000,64.200000,0,1,0,0,1,0,0
39997,13.1,65.600000,38.100000,0,0,0,1,0,0,0
39998,14.1,74.900000,65.456209,1,0,0,0,0,0,1
39999,11.8,55.100000,68.500000,0,1,0,1,0,0,0