<a href="https://colab.research.google.com/github/rahulpirwani7/Student-Pass-Fail-Prediction/blob/main/Passandfailpredication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [539]:
import kagglehub
import os
import pandas as pd

path = kagglehub.dataset_download("kundanbedmutha/exam-score-prediction-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'exam-score-prediction-dataset' dataset.
Path to dataset files: /kaggle/input/exam-score-prediction-dataset

In [540]:
files = os.listdir(path)

print("\nFiles in the dataset:")
for file in files:
    print(file)

csv_file = None
for file in files:
    if file.endswith(".csv"):
        csv_file = file
        break

if csv_file is None:
    print("No CSV file found in the dataset.")
else:
    file_path = os.path.join(path, csv_file)
    df = pd.read_csv(file_path)

Files in the dataset:
Exam_Score_Prediction.csv

In [541]:
df.columns=df.columns.tolist()
df.drop('student_id',axis=1,inplace=True)

In [542]:
df

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,18,other,bba,6.50,71.3,yes,5.0,good,self-study,low,easy,86.5
19996,18,male,b.com,3.71,41.6,no,5.9,average,coaching,medium,moderate,60.9
19997,19,other,diploma,7.88,68.2,yes,4.6,poor,group study,low,easy,64.5
19998,19,male,bba,4.60,76.3,no,6.1,good,self-study,medium,moderate,79.0
19999,20,male,b.sc,7.50,47.9,yes,7.5,poor,coaching,medium,moderate,71.0

In [543]:
df.describe()

                age   study_hours  class_attendance  sleep_hours    exam_score
count  20000.000000  20000.000000      20000.000000  20000.00000  20000.000000
mean      20.473300      4.007604         70.017365      7.00856     62.513225
std        2.284458      2.308313         17.282262      1.73209     18.908491
min       17.000000      0.080000         40.600000      4.10000     19.599000
25%       18.000000      2.000000         55.100000      5.50000     48.800000
50%       20.000000      4.040000         69.900000      7.00000     62.600000
75%       22.000000      6.000000         85.000000      8.50000     76.300000
max       24.000000      7.910000         99.400000      9.90000    100.000000

In [544]:
X=['gender','study_method','course']
df = pd.get_dummies(
    df,
    columns=X,
    prefix="",
    prefix_sep="",
    dtype=int
)

In [545]:
df.describe()

,age,study_hours,class_attendance,sleep_hours,exam_score,female,male,other,coaching,group study,mixed,online videos,self-study,b.com,b.sc,b.tech,ba,bba,bca,diploma
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000
mean,20.473300,4.007604,70.017365,7.00856,62.513225,0.328950,0.334750,0.336300,0.201800,0.196100,0.194700,0.203450,0.203950,0.143200,0.143900,0.139900,0.144800,0.141800,0.14510,0.141300
std,2.284458,2.308313,17.282262,1.73209,18.908491,0.469844,0.471915,0.472455,0.401354,0.397055,0.395979,0.402574,0.402942,0.350285,0.350997,0.346892,0.351908,0.348854,0.35221,0.348339
min,17.000000,0.080000,40.600000,4.10000,19.599000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,18.000000,2.000000,55.100000,5.50000,48.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,20.000000,4.040000,69.900000,7.00000,62.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
75%,22.000000,6.000000,85.000000,8.50000,76.300000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
max,24.000000,7.910000,99.400000,9.90000,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000

In [546]:
df["Passed"] = df["exam_score"].apply(lambda x: "Passed" if x >= 70 else "Failed")
df.drop("exam_score", axis=1, inplace=True)

In [547]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# numeric_cols = [
#     "Study Hours per Week",
#     "Attendance Rate",
#     "Previous Grades"
# ]

# X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
# X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [548]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X=['internet_access','Passed']
for i in X:
    df[i]=le.fit_transform(df[i])

df["sleep_quality"] = df["sleep_quality"].map({
    "poor": 0,
    "average": 1,
    "good": 2
})

df['facility_rating']=df['facility_rating'].map({
    'low':0,
    'medium':1,
    'high':2
})

df['exam_difficulty']=df['exam_difficulty'].map({
    'easy':0,
    'moderate':1,
    'hard':2
})

In [549]:
from sklearn.model_selection import train_test_split
X = df.drop('Passed', axis=1)
y = df['Passed']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [550]:
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier

model = SGDClassifier(
    loss="log_loss",      # Logistic Regression
    learning_rate="constant",
    eta0=0.01,            # Learning rate
    max_iter=10000,
    random_state=42
)

model.fit(X_train, y_train)

SGDClassifier(eta0=0.01, learning_rate='constant', loss='log_loss',
              max_iter=10000, random_state=42)

In [551]:
df

,age,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,facility_rating,exam_difficulty,female,male,...,online videos,self-study,b.com,b.sc,b.tech,ba,bba,bca,diploma,Passed
0,17,2.78,92.9,1,7.4,0,0,2,0,1,...,0,0,0,0,0,0,0,0,1,0
1,23,3.37,64.8,1,4.6,1,1,1,0,0,...,1,0,0,0,0,0,0,1,0,0
2,22,7.88,76.8,1,8.5,0,2,1,0,1,...,0,0,0,1,0,0,0,0,0,1
3,20,0.67,48.4,1,5.8,1,0,1,0,0,...,1,0,0,0,0,0,0,0,1,0
4,20,0.89,71.6,1,9.8,0,0,1,1,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,18,6.50,71.3,1,5.0,2,0,0,0,0,...,0,1,0,0,0,0,1,0,0,1
19996,18,3.71,41.6,0,5.9,1,1,1,0,1,...,0,0,1,0,0,0,0,0,0,0
19997,19,7.88,68.2,1,4.6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19998,19,4.60,76.3,0,6.1,2,1,1,0,1,...,0,1,0,0,0,0,1,0,0,1
19999,20,7.50,47.9,1,7.5,0,1,1,0,1,...,0,0,0,1,0,0,0,0,0,1

In [552]:
y_prob = model.predict_proba(X_test)[:, 1]


threshold = 0.5
y_pred = (y_prob >= threshold).astype(int)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred) )

Accuracy: 0.7631666666666667

In [553]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[2525 1269]
 [ 152 2054]]

In [554]:
y_prob = model.predict_proba(X_test)

print(y_prob[:10])

[[1.54773283e-09 9.99999998e-01]
 [8.88178420e-16 1.00000000e+00]
 [9.80973990e-03 9.90190260e-01]
 [1.00000000e+00 1.42029762e-24]
 [4.21884749e-15 1.00000000e+00]
 [1.00000000e+00 1.97205552e-18]
 [3.19744231e-14 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [1.00000000e+00 6.30329339e-34]
 [9.26155048e-01 7.38449520e-02]]

In [555]:
df["Passed"].value_counts()

Passed
0    12783
1     7217
Name: count, dtype: int64

In [556]:
print(y_train.value_counts())

Passed
0    8989
1    5011
Name: count, dtype: int64

In [557]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(14000, 23)
(6000, 23)
(14000,)
(6000,)

In [558]:
print(X_train.head())

       age  study_hours  class_attendance  internet_access  sleep_hours  \
17192   24         3.32              73.3                1          7.7
3765    20         6.39              80.9                0          8.6
11228   20         6.43              44.6                1          7.4
12396   24         2.95              66.8                1          9.6
12517   20         1.19              47.1                1          8.7

       sleep_quality  facility_rating  exam_difficulty  female  male  ...  \
17192              0                1                1       0     1  ...
3765               1                0                0       1     0  ...
11228              0                0                1       0     0  ...
12396              0                2                1       0     0  ...
12517              0                0                0       0     0  ...

       mixed  online videos  self-study  b.com  b.sc  b.tech  ba  bba  bca  \
17192      0              1           0      0     0       0   0    0    0
3765       0              0           1      0     0       0   0    0    1
11228      0              1           0      0     0       1   0    0    0
12396      0              0           1      0     0       0   1    0    0
12517      0              0           1      0     0       0   0    0    0

       diploma
17192        1
3765         0
11228        0
12396        0
12517        1

[5 rows x 23 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

models = {
    "Logistic Regression": LogisticRegression(max_iter=5000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42)
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(name)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("-"*40)

Logistic Regression
Accuracy: 0.8368333333333333
----------------------------------------
Decision Tree
Accuracy: 0.7755
----------------------------------------

In [ ]:
print(df.corr(numeric_only=True)["Passed"].sort_values(ascending=False))